console.log("Assignments 02.1");
var bankName;
console.log("=====log value on before initialisation====");
console.log(bankName);
console.log("        ");
console.log("=====log value on after initialisation=====");
bankName="SBI Bank";
console.log(bankName);
console.log(typeof bankName); 
console.log("   =========================================     ");   
console.log("Assignments 02.2");
var marks="90%";
console.log(typeof marks);
console.log("   =========================================     ");
console.log("Assignments 02.3");
var isWorking;
console.log("=====log value on before initialisation====");
console.log(isWorking);
console.log("        ");
console.log("=====log value on after initialisation=====");
isWorking="true";
console.log(isWorking);
console.log("=====3.1 type of isWorking=====");
console.log(typeof true); 
console.log("   =========================================     ");
console.log("Assignments 02.4.a");
var totalCount="Hundred and Seven";
console.log(totalCount,typeof totalCount); 
console.log("Assignments 02.4.b");
totalCount="107";
console.log(totalCount,typeof 107);

